[versions]
activityCompose = "1.13.0"
agp = "9.4.1"
appcompat = "1.8.0"
composeBom = "2026.09.00"
constraintlayout = "2.2.2"
coreSplashscreen = "1.2.0"
fragmentKtx = "1.9.1"
kotlin = "2.4.20"
material = "1.14.0"
xmlparser = "23.26.3.0.0"
coreKtx = "1.19.1"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activityCompose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.8.0" }
material = { module = "com.google.android.material:material", version.ref = "material" }
xmlparserv2 = { module = "com.oracle.database.xml:xmlparserv2", version.ref = "xmlparser" }

kokuban = { module = "io.github.digorydoo:kokuban", version = "0.9.2" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
