package io.github.digorydoo.goigoi.core

/**
 * Categories should not be technical, i.e. NOUN, VERB, etc. would not be good categories, because it isn't generally
 * good to group them together.
 */
enum class WordCategory(val id: Int) {
    ANIMAL(1),
    AQUATIC(2),
    ARTS(3),
    ASTRONOMY(4),
    BEACH(5),
    BEVERAGE(6),
    BIRD(7),
    BODY(8),
    BUSINESS(9),
    CITY(10),
    CLEANING(11),
    COLOUR(12),
    COOKING(13),
    COUNTRYSIDE(14),
    CRIME(15),
    CULTURE(16),
    DAYS_OF_THE_WEEK(17),
    DIRECTIONS(18),
    DIY(19),
    EDUCATION(20),
    EMPLOYMENT(21),
    ENTERTAINMENT(22),
    FACTORY(23),
    FAMILY(24),
    FASHION(25),
    FEET(26),
    FINANCES(27),
    FIRE(28),
    FOOD(29),
    GAMES(30),
    GARDEN(31),
    GASTRONOMY(32),
    GENERAL(33),
    GEOGRAPHY(34),
    GOING_OUT(35),
    GOVERNMENT(36),
    HANDS(37),
    HAPPINESS(38),
    HEALTH(39),
    HEARING(40),
    HISTORICAL(41),
    HOBBY(42),
    HOLIDAYS(43),
    HOME(44),
    INSECT(45),
    LIFE(46),
    LIGHT(47),
    LINGUISTICS(48),
    LITERATURE(49),
    LOOKING(50),
    MANGA_ANIME(51),
    MATHS(52),
    MEETINGS(53),
    MILITARY(54),
    MONTHS(55),
    MOOD(56),
    MOTION(57),
    NATURE(58),
    NEWS(59),
    NOT_GOOD(60),
    OBJECTS(61),
    OCCUPATIONS(62),
    OLD_FASHIONED(63),
    ONOMATOPOEIA(64),
    PEOPLE(65),
    PHYSICS(66),
    PLANT(67),
    POLITICS(68),
    QUARREL(69),
    RELATIONSHIPS(70),
    SCENERY(71),
    SCIENCE(72),
    SEASONS(73),
    SHOPPING(74),
    SPORTS(75),
    TALKING(76),
    TECHNICAL(77),
    TEMPERATURE(78),
    THINKING(79),
    TIME(80),
    TOP_WORDS(81),
    TRADE(82),
    TRANSPORTATION(83),
    TRAVELLING(84),
    WEATHER(85),
    WORK(86),
    WRITING(87),
    ;

    val text = name.lowercase().replace("_", "-")

    companion object {
        fun fromInt(id: Int): WordCategory? =
            entries.find { it.id == id }

        fun fromString(s: String): WordCategory? =
            entries.find { it.text == s }
    }
}
