package io.github.digorydoo.goigoi.core.db

/**
 * Categories should not be technical, i.e. NOUN, VERB, etc. would not be good categories, because it isn't generally
 * good to group them together.
 */
enum class WordCategory(val id: Int) {
    ANIMAL(1),
    AQUATIC(2),
    ARTS(3),
    ASTRONOMY(4),
    BEACH(5),
    BEVERAGE(6),
    BIRD(7),
    BODY(8),
    BUSINESS(9),
    CITY(10),
    CLEANING(11),
    COLOUR(12),
    COOKING(13),
    COUNTRYSIDE(14),
    CRIME(15),
    CULTURE(16),
    DAYS_OF_THE_WEEK(17),
    DIRECTIONS(18),
    DIY(19),
    EDUCATION(20),
    EMPLOYMENT(21),
    ENTERTAINMENT(22),
    FACTORY(23),
    FAMILY(24),
    FASHION(25),
    FEET(26),
    FINANCES(27),
    FIRE(28),
    FOOD(29),
    FORMAL(30),
    GAMES(31),
    GARDEN(32),
    GASTRONOMY(33),
    GENERAL(34),
    GEOGRAPHY(35),
    GOING_OUT(36),
    GOVERNMENT(37),
    HANDS(38),
    HAPPINESS(39),
    HEALTH(40),
    HEARING(41),
    HISTORICAL(42),
    HOBBY(43),
    HOLIDAYS(44),
    HOME(45),
    INSECT(46),
    LIFE(47),
    LIGHT(48),
    LINGUISTICS(49),
    LITERATURE(50),
    LOOKING(51),
    MANGA_ANIME(52),
    MATHS(53),
    MEETINGS(54),
    MILITARY(55),
    MONTHS(56),
    MOOD(57),
    MOTION(58),
    NATURE(59),
    NEWS(60),
    NOT_GOOD(61),
    OBJECTS(62),
    OCCUPATIONS(63),
    OLD_FASHIONED(64),
    ONOMATOPOEIA(65),
    PEOPLE(66),
    PHYSICS(67),
    PLANT(68),
    POLITICS(69),
    QUARREL(70),
    RELATIONSHIPS(71),
    SCENERY(72),
    SCIENCE(73),
    SEASONS(74),
    SHOPPING(75),
    SPORTS(76),
    TALKING(77),
    TECHNICAL(78),
    TEMPERATURE(79),
    THINKING(80),
    TIME(81),
    TOP_WORDS(82),
    TRADE(83),
    TRANSPORTATION(84),
    TRAVELLING(85),
    WEATHER(86),
    WORK(87),
    WRITING(88),
    ;

    val text = name.lowercase().replace("_", "-")

    companion object {
        fun fromInt(id: Int): WordCategory? =
            entries.find { it.id == id }

        fun fromString(s: String): WordCategory? =
            entries.find { it.text == s }
    }
}
